language: go
sudo: false

go:
- "1.11.x"

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

before_script:
- go vet ./...

script:
- go test -v -race ./...  # Run all the tests with the race detector enabled